// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoa-Gk-wz7NyT-h2PNvlOjebkzGjH5rgI',
    appId: '1:1006975602523:web:b08510b6bc47313c88147e',
    messagingSenderId: '1006975602523',
    projectId: 'smart-class-4a13c',
    authDomain: 'smart-class-4a13c.firebaseapp.com',
    storageBucket: 'smart-class-4a13c.firebasestorage.app',
    measurementId: 'G-2JYBR96TNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGn2ksBeMIhOvZGC3Qa5S_fvwqUUy6FRY',
    appId: '1:1006975602523:android:695512e8901bf6e888147e',
    messagingSenderId: '1006975602523',
    projectId: 'smart-class-4a13c',
    storageBucket: 'smart-class-4a13c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7bfVy2aaFdcNvNymy1L7Oeg8uNfmfe6s',
    appId: '1:1006975602523:ios:b136c58ae016c94a88147e',
    messagingSenderId: '1006975602523',
    projectId: 'smart-class-4a13c',
    storageBucket: 'smart-class-4a13c.firebasestorage.app',
    iosBundleId: 'com.example.smartClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7bfVy2aaFdcNvNymy1L7Oeg8uNfmfe6s',
    appId: '1:1006975602523:ios:b136c58ae016c94a88147e',
    messagingSenderId: '1006975602523',
    projectId: 'smart-class-4a13c',
    storageBucket: 'smart-class-4a13c.firebasestorage.app',
    iosBundleId: 'com.example.smartClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoa-Gk-wz7NyT-h2PNvlOjebkzGjH5rgI',
    appId: '1:1006975602523:web:909b137bb8d1937088147e',
    messagingSenderId: '1006975602523',
    projectId: 'smart-class-4a13c',
    authDomain: 'smart-class-4a13c.firebaseapp.com',
    storageBucket: 'smart-class-4a13c.firebasestorage.app',
    measurementId: 'G-TDZK9RSRF8',
  );
}
